<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$config['uri_segment']       = 3;
$config['num_links']         = 5;
$config['full_tag_open']     = '<div id="pagination" class="pagination">';
$config['full_tag_close']    = '</div>';
$config['first_link']        = 'Primer';
$config['first_tag_open']    = '';
$config['first_tag_close']   = '';
$config['last_link']         = 'Ultimo';
$config['last_tag_open']     = '';
$config['last_tag_close']    = '';
$config['next_link']         = '&gt;';
$config['next_tag_open']     = '';
$config['next_tag_close']    = '';
$config['prev_link']         = '&lt;';
$config['prev_tag_open']     = '';
$config['prev_tag_close']    = '';
$config['cur_tag_open']      = '<b>';
$config['cur_tag_close']     = '</b>';
$config['num_tag_open']      = '';
$config['num_tag_close']     = '';
$config['page_query_string'] = FALSE;